config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :trips, only: [:index] do
    collection do
      get :api_data
    end
  end
  root 'trips#api_data'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  require 'rest-client'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
  
  def authenticate_api(pass, email)
    url= "https://jettymx-st.herokuapp.com/api/drivers/session"
    response = RestClient.post url, {driver: {email: email, password: pass}}.to_json, {content_type: :json, accept: :json}
    response = JSON.parse(response.to_str)
    if authentication_email.nil?
      update(authentication_email: response["email"], authentication_token: response["auth_token"])
    else
      update(authentication_token: response["auth_token"])
    end
  rescue RestClient::Exception
    "No autorizado"
  end

  def get_data_from_api
    url= "https://jettymx-st.herokuapp.com/api/drivers/trips"
    response = RestClient.get url, {authorization: "Token #{authentication_token}, email=#{authentication_email}"}
  rescue RestClient::Exception
    false
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :driver
  has_many :trip_stops
  #group by day
  #scope :ordered, ->{order(created_at: :asc).group_by{ |t| t.created_at.day}}
  #only order
  scope :ordered, ->{order(created_at: :asc)}

end

app/models/trip_stop.rb
class TripStop < ApplicationRecord
  belongs_to :trip
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_driver!

  protected
    def after_sign_in_path_for(resource)
      resource.authenticate_api(params[:driver][:password], params[:driver][:email])
      root_path
    end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips =[]
    Trip.ordered.each do |trip|
      @trips << {id: trip.id, name:trip.name, price: trip.price, date: trip.date.strftime("%Y-%m-%d"), time: trip.date.strftime("%I:%M %p"),
                driver: trip.driver,
                trip_stops: trip.trip_stops}
    end
    
    @trips = @trips.to_json
  end

  def api_data
    if current_driver.get_data_from_api
      @trips = current_driver.get_data_from_api
    else
      sign_out
      redirect_to root_path 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= image_tag "logo-jetty", class: "img-fluid nav"%>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Datos locales", trips_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Datos Api", api_data_trips_path, class: "nav-link" %>
      </li>
    </ul>
    <div class="session">
      <%= link_to "Cerrar sesión", destroy_driver_session_path, method: :delete, class: "nav-link" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestJetty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= "container">
      <%= render "layouts/nav" if driver_signed_in? %>
      <div class="row justify-content-md-center">
        <div>
          <%= yield %>
        </div>
      </div>
  </body>
</html>

app/views/shared/trips/_list.html.erb
<% JSON.parse(@trips).group_by{ |t| t["date"]}.to_a.reverse.each_with_index do |trip, index| %>
  <div class="alert alert-primary" role="alert">
    <%= trip[0].to_date.strftime("%d %B")  %>
  </div>
  <% trip[1].each_with_index do |trip_day, i| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= trip_day["name"] %></h5>
        <span>Horario de salida </span>
        <p class="card-text"><%= trip_day["time"] %></p>
        <p class="card-text">
          <strong>Inicio: </strong><%= trip_day["trip_stops"].first["address"] if trip_day["trip_stops"].present? %>
          <br />
          <strong>Termina: </strong><%= trip_day["trip_stops"].last["address"] if trip_day["trip_stops"].present? %>
        </p>
        <% if trip_day["vehicle"].present? %>
          <p class="card-text">
            <h6>Vehículo</h6>
            <strong>Modelo: </strong><%= trip_day["vehicle"]["model"] %>
            <br />
            <strong>Placas: </strong><%= trip_day["vehicle"]["plate"] %>
          </p>
        <% end %>
        <% if trip_day["trip_stops"].present? %>
          <%= render "shared/trips/stops", i: i+index, stops: trip_day["trip_stops"] %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/trips/_stops.html.erb
<div id="accordion">
  <div class="card">
    <div class="card-header" id="heading<%= i %>">
      <h5 class="mb-0">
        <button class="btn btn-primary collapsed" data-toggle="collapse" data-target="#collapse<%= i %>" aria-expanded="false" aria-controls="collapse<%= i %>">
          Ver paradas y usuarios
        </button>
      </h5>
    </div>
    <div id="collapse<%= i %>" class="collapse" aria-labelledby="heading<%= i %>" data-parent="#accordion">
      <div class="card-body">
        <h5>Paradas </h5>
        <ul class= "list-group list-group-flush">
          <% stops.each do |stop| %>
            <li class="list-group-item">
              <%= stop["address"] %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/trips/api_data.html.erb
<div class="col title">
  <h3>Corridas asignadas</h3>
</div>
<%= render "shared/trips/list", trips: @trips %>

app/views/trips/index.html.erb
<div class="col title">
  <h3>Corridas asignadas</h3>
</div>
<%= render "shared/trips/list", trips: @trips %>